---
# tasks file for httpd
- name: creates hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ creates_hosts }}"
    state: present

- name: installing apache
  package:
    name: "{{ apache_pkg }}"
    state: latest

- name: Copy apache config 
  template:
    src: website.conf.j2
    dest: "{{ j2_dest }}"

- name: create a directory for ansible
  file:
    path: "{{ item }}"
    state: directory
    owner: apache
    group: apache
  with_items:
    - "{{ create_dir1 }}"
    - "{{ create_dir2 }}"

- lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "{{ apache_dir_index }}"    
    line: "{{ apache_dir_index }} index.php"

- name: apache restarted
  service:
    name: httpd
    state: "{{ apache_restarted }}"   
