---
all:
  vars:
    db_pass1: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      62643130626136303332613165306366343433353737343566653962623737316339343531343336
      3936666135393962313132653933386139613534386439300a323632366439353433383538653833
      62626461626364366535623238363236613831633434663734633466643138386530633332313436
      3238666236616463300a663762333366636130333864303237613436333436303762326230343633
      3532
    db_pass2: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39356231666266373031366233303062653736356134386261316637356239366632313838346530
      3834656234393631303838363964303366653963393964380a346364653732383634643132313034
      61666166643365613038366464396562653039326337326263616661303238373633373132376134
      6236363138626638660a356232613433376533663936346461386131636362303066363663666662
      3834
servers:
  children:
    host1:
      hosts: centos.host
      vars:
        remote_user: centos
        doc_root1: '/var/www/html/website1'
        doc_root2: '/var/www/html/website2'
        apache_conf_dest: /etc/httpd/conf.d/website.conf
        apache_owner: apache
        apache_group: apache
        conf_file: /etc/httpd/conf/httpd.conf
        server1: website1.com
        server2: website2.com
        error_custom: /var/log/httpd
        error_1: "{{ error_custom }}/website1.com_error.logs"
        error_2: "{{ error_custom }}/website2.com_error.logs"
        custom_1: "{{ error_custom }}/website1com_access.log"
        custom_2: "{{ error_custom }}/website2com_access.log"
        web_url1: 'website1'
        web_url2: 'website2'
        db_name1: 'web1'
        db_name2: 'web2'
        database_1: web1
        database_2: web2
        db_user1: 'website1'
        db_user2: 'website2'
        apache_restart: httpd
        pkg_mysql: mariadb-server, mysql, MySQL-python
        db_service: mariadb
        apache_pkg: httpd
        apache_service: httpd
        pkg_php: php, php-mysqlnd 
    host2:
      hosts: ubuntu.host
      vars:
        remote_user: ubuntu
        doc_root1: '/var/www/html/website3'
        doc_root2: '/var/www/html/website4'
        apache_conf_dest: /etc/apache2/sites-enabled/website.conf
        apache_owner: www-data
        apache_group: www-data
        server1: website3.com
        server2: website4.com
        conf_file: /etc/apache2/apache2.conf   
        error_1: "{{ error_custom }}/website3.com_error.logs"
        error_2: "{{ error_custom }}/website4.com_error.logs"
        error_custom: /var/log/apache2
        custom_1: "{{ error_custom }}/website3com_access.log"
        custom_2: "{{ error_custom }}/website4com_access.log"
        web_url1: 'website3'
        web_url2: 'website4'
        db_name1: 'web3'
        db_name2: 'web4'
        database_1: web3
        database_2: web4
        db_user1: 'website3'
        db_user2: 'website4'
        apache_restart: apache2
        pkg_mysql: mysql-server,python-mysqldb
        db_service: mysql
        apache_pkg: apache2
        apache_service: apache2
        pkg_php: php,php-mysql
