---
# tasks file for mysql
- name: install mysql
  package:
    name: "{{ pkg_mysql }}"
    state: latest
  tags: [ mysql_install ]

- name: restart mysqld
  service:
    name: "{{ restarted_mysql }}"        
    state: restarted
  tags: [ restart_mysqld ]

- name: creating database in mysql
  mysql_db:
    name: '{{ item }}'
    state: present
  with_items:
    - "{{ database_1 }}"
    - "{{ database_2 }}"
  tags: [ mysql_db ]

- name: creating users in mysql     
  mysql_user:
    name: "{{ item.0 }}"
    password: "{{ item.1 }}"
    priv: "{{ priv }}"
    state: present 
  with_items:  
  - { 0: "{{ db_user1 }}", 1: "{{ db_password1 }}" }
  - { 0: "{{ db_user2 }}", 1: "{{ db_password2 }}" }
    tags: [ mysql_user ]  
