---
# tasks file for php
- name: installing php
  package:
    name: "{{ pkg_php }}"
    state: latest
   
- name: domwload wp-cli    
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /bin/wp
    mode: 0777

- name: wp domwloads 
  shell: wp core download
  args:
    chdir: "{{ item.0 }}"
    creates: "{{ item.1 }}/index.php"
  with_items:
    - { 0: '/var/www/html/website1', 1: '/var/www/html/website1' }
    - { 0: '/var/www/html/website2', 1: '/var/www/html/website2' }

- name: Create a wp-config.php file
  shell:  "wp core config --dbname={{ item.0 }} --dbuser={{ item.1 }} --dbpass={{ item.2 }} --dbhost=localhost --dbprefix=wp_"
  args:
    chdir: "{{ item.3 }}"
    creates: "{{ item.3 }}/wp-config.php"
  with_items:
    - { 0: 'web1', 1: 'website1', 2: 'testone', 3: '/var/www/html/website1' }
    - { 0: 'web2', 1: 'website2', 2: 'testtwo', 3: '/var/www/html/website2' } 
- name: Run the installation           
  shell: 'wp core install --url="http://{{ item.0 }}.com" --title="{{ item.1 }}" --admin_user="{{ item.2 }}" --admin_password="{{ item.3 }}" --admin_email="{{ item.4 }}.com"'
  args:
    chdir: "{{ item.5 }}"
  with_items: 
    - { 0: 'website1', 1: 'testsite1', 2: 'web1', 3: 'qwertypad', 4: 'test1@test.com', 5: '/var/www/html/website1' }
    - { 0: 'website2', 1: 'testsite2', 2: 'web2', 3: 'qwertypad1999', 4: 'test2@test.com', 5: '/var/www/html/website2' }
