---
# tasks file for httpd

- name: Update apt
  shell: apt-get update
  when: ansible_distribution == "Ubuntu"

- name: Installing apache
  package:
    name: "{{ apache_pkg }}"
    state: latest
  tags: [ install_apache ]
  notify:
    - Restart apache

- name: Copy apache config 
  template:
    src: website.conf.j2
    dest: "{{ apache_conf_dest }}"
  tags: [ apache_config ]
  notify:
    - Restart apache

- name: create document roots
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ apache_owner }}"
    group: "{{ apache_group }}"
  with_items:
    - "{{ doc_root1 }}"
    - "{{ doc_root2 }}"
  tags: [ doc_roots ]

- lineinfile:
    path: "{{ conf_file }}"
    regexp: "{{ apache_dir_index }}"    
    line: "{{ apache_dir_index }} index.php"
  tags: [ dir_index ]
  notify:
    - Restart apache

