---
# tasks file for httpd
- name: Add domains in hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ creates_hosts }}"
    state: present
  tags: [ add_domains ]

- name: Installing apache
  package:
    name: "{{ apache_pkg }}"
    state: latest
  tags: [ install_apache ]
  notify:
    - Restart apache

- name: Copy apache config 
  template:
    src: website.conf.j2
    dest: "{{ j2_dest }}"
  tags: [ apache_config ]
  notify:
    - Restart apache

- name: create document roots
  file:
    path: "{{ item }}"
    state: directory
    owner: apache
    group: apache
  with_items:
    - "{{ create_dir1 }}"
    - "{{ create_dir2 }}"
  tags: [ doc_roots ]

- lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "{{ apache_dir_index }}"    
    line: "{{ apache_dir_index }} index.php"
  tags: [ dir_index ]
  notify:
    - Restart apache

