---
- hosts: servers
  gather_facts: yes
  remote_user: "{{ remote_user }}"
  become: true
  become_user: root
  roles:
    - { role: httpd, tags: httpd }
    - { role: mysql, tags: mysql }
    - { role: php, tags: php } 
